### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by wajahat57** [kurapan/EAST#1]
Hi
Thanks for sharing the code.
I am getting syntax error on line 101 in train.py:
`        pred_score_maps, pred_geo_maps = self.model.predict([data[0][0], data[0][1], data[0][2], data[0][3])
`
I am using Keras 2.1.5
with TensorFlow  1.9.0
and Python 3.5.4 on windows Windows 10

**Comment by kurapan** [comment]
Sorry, I made a mistake when copying files for upload and pushed changes with files that weren't up to date. It should be okay now.
