### ISSUE TITLE
Test accuracy and validation accuracy

### ISSUE THREAD

**Issue by niddal-imam** [kurapan/EAST#11]
How can I get both test accuracy and validation accuracy for each epoch?

**Comment by kurapan** [comment]
By accuracy you mean the metrics (precision, recall, F-score) for the model? I haven't implemented evaluation of the metrics during the training process if that is what you mean.
I might do that later when I have some spare time but not really anytime soon.

**Comment by niddal-imam** [comment]
Yes, the model’s precision, recall and F-score. 
Thanks

**Comment by kurapan** [comment]
Yeah, I haven't automatized that process. For now you have to use the `eval.py` to evaluate a model checkpoint and use the evaluation code provided by ICDAR to evaluate the results output by `eval.py`.
