### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Akhilkottappuram** [kurapan/EAST#12]
/home/saju/.local/lib/python3.6/site-packages/keras_applications/resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '

**Comment by kurapan** [comment]
This is just Keras user warning in Keras 2.2+ when using ResNet50. Nothing wrong here. 
I mention this in the readme. 
I wrote the code before Keras 2.2 was released and the Keras implementation did not work correctly for arbitrary input shape at that time, so I had to add ZeroPadding in one place to correct the shape.
