### ISSUE TITLE
Training is stuck at epoch 1

### ISSUE THREAD

**Issue by nandhiniS87** [kurapan/EAST#16]
the model summary is printed and training is stuck after printing epoch 1..

**Comment by kurapan** [comment]
I will need more details about what data you use, how long you've waited, what are your specs, what versions of Keras and TF you use, etc. The more details you give, the higher the chance we can find a solution to the issue. I haven't experienced such a problem so I can't offer or suggest any solution with such few information available.

**Comment by nandhiniS87** [comment]
Thanks for the reply. Am using keras 2.2.4 and tensorflow 1.17. My training
data is ICDAR2015. I have only one GPU and since if I keep
use_multiprocessing = true it gave errors and switched it to false. I
waited for more than 3 hours. Still am not able to fix it. It is looping
inside the fit_generator. Am help on this will be very much useful.

Thanks

**Comment by kurapan** [comment]
Is it TF 1.7? I think the latest one is 1.13. Could you try it with Keras 2.1.5 and TF 1.4 just in case for the start?
What kind of errors have you experienced with use_multiprocessing=True? If it's just saying
`UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data`
then you don't have to worry. The code uses a threadsafe generator so that data doesn't get duplicated. However, Keras shows this warning unless you use the Keras Sequence class, which also ensures that data doesn't get duplicated.
Btw do you use Linux or Windows?

**Comment by nandhiniS87** [comment]
Ran out of input error occurs when using multi processing. Let me try with
the versions you suggested. Am using Windows 10.

**Comment by kurapan** [comment]
I see. I haven't tried it with Windows and don't even have any means to try.
I think I've read somewhere that `use_multiprocessing=True` doesn't work well or at all in Windows.
Could you post a copypaste of the exact error it prints when using multiprocessing?

**Comment by nandhiniS87** [comment]
I will post all the screen shots tomorrow as I am away from the machine
now. Multi processing and forking spawning are creating error in windows.
As a work around I have put the use_multiprocessor=false. Where could be
the problem here? Loading batches of data or fitting them?

**Comment by kurapan** [comment]
It seems to have problem loading data if it's stuck at showing `Epoch 1/XXX` without any progress bar.
Do you use validation data?

**Comment by nandhiniS87** [comment]
No.. am not using any validation data.

**Comment by kurapan** [comment]
I see. Thanks for the clarification. I'll try to think about it, but I'm not able to suggest anything now. It should work regardless of whether you use multiprocessing or not.
Could you post tomorrow what it prints when you terminate it by pressing Ctrl+C when it gets stuck? It might get stuck somewhere in Windows where it doesn't get stuck on Ubuntu.

**Comment by nandhiniS87** [comment]
I tried printing the image name(im_fn) and text file name.. it loops
infinitely.. let me provide you screenshots for better understanding

**Comment by nandhiniS87** [comment]
Hi,

I have installed keras 2.1.5 as suggested. But could not downgrade
tensorflow to 1.4 due to compatibility issues and am using tensorflow 1.8
currently.

The screenshots like you asked.

1) when am using use_multiprocessing=False, and i interrupted the training
by ctrl + C

[image: image.png]

2) when trying to print the image name and text file name, it is looping
infinitely.

[image: image.png]

What could be the problem here? Should I be looking into the generator
function in the data_processor?
Please help me on this.

Meanwhile, am gonna try running the program on Ubuntu machine today.

Thanks

**Comment by kurapan** [comment]
I think that github comments don't support image attachments. Could you copypaste the text or upload the screenshots somewhere?

**Comment by nandhiniS87** [comment]
i made it work. there was some problem in loading the images and gt files. i fixed it and it is training now. thanks for your help.

**Comment by kurapan** [comment]
You're welcome!

**Comment by sjakati98** [comment]
@nandhini-ns1808900 Could you please describe your solution. I'm also getting the same problem, my training hangs at the first epoch.
