### ISSUE TITLE
Fine-tuning the model

### ISSUE THREAD

**Issue by niddal-imam** [kurapan/EAST#18]
I would like to fine-tune the model with my own data, so I am wondering what is the better way to do that. Should I just train the model with my data, or should I train just the last layers?

**Comment by kurapan** [comment]
I guess it depends.
If the data you have is scene text data similar to the ICDAR dataset images, then
a) if you have a lot of data, then there's probably no point in fine-tuning and better to train the whole model from scratch (the ICDAR dataset is small, so there's not much benefit in finetuning a model pretrained on that)
b) if you don't have a lot of data, then using the pretrained model might be better, but I would finetune the whole model, not just the last layers. Or maybe first finetune on the last layers, and then on the whole model.
If the data is not very similar, I would just train the model from scratch on it.

**Comment by niddal-imam** [comment]
Yes, my data is different, so as you suggest I will finetune the whole the whole model.

Thanks kurapan

**Comment by kurapan** [comment]
You’re welcome
