### ISSUE TITLE
loss is too low 

### ISSUE THREAD

**Issue by WJinhai** [kurapan/EAST#19]
I train my dataset , the result show 723/1625 [============>.................] - ETA: 11:46 - loss: 0.0012 - pred_score_map_loss: 2.9373e-04 - pred_geo_map_loss:1.8351e-04 . I want to know whether this is right ?

**Comment by kurapan** [comment]
It’s possible on easy data such as some documents or other printed materials.

**Comment by NidhiSultan** [comment]
Hi  @kurapan, my loss has started going down after 16 epoch, it shows nan for all losses. Is that normal? Also, I tried to test the model after the 10th epoch it doesn't give me any results even if I decrease the score map. Please help!
