### ISSUE TITLE
Training the model using my own data

### ISSUE THREAD

**Issue by niddal-imam** [kurapan/EAST#21]
Hi kurapan,

I have built my own data, which consist of 200 images, and I trained the model for 80 iterations. However, the model performance have not improved; it became worst. Should I train the model more or collect more data?

Thanks

**Comment by kurapan** [comment]
200 images is definitely a small number and might be very far from enough to be able to train a model with solid performance.
I believe you mean 80 epochs. I run training for several hundred epochs when using ICDAR data to achieve optimal performance. However, you have several times less data for training so it's possible that training is close to convergence after 80 epochs.

**Comment by kalai2033** [comment]
@niddal-imam Hey im also using my own dataset for training. Can i know how did you do annotations for your images. Is there any specific tool that you used for it?
