### ISSUE TITLE
which value of mean image subtraction, I need to select if I use gray scale image?

### ISSUE THREAD

**Issue by lerndeep** [kurapan/EAST#28]
I am planning to train this network on the grayscale image but I am wondering about to select mean image subtraction value if I used the grayscale images.

**Comment by NidhiSultan** [comment]
Hi @lerndeep  and @kurapan ,
Were you able to train this on normal images? I keep getting Number of  Validation image  as 0 and not able to resolve the issue. 
Can you help with the same?

Thanks in advance!!!!!

**Comment by kurapan** [comment]
Try just scaling the data to <-1; 1> range.
