### ISSUE TITLE
Error: timeout value too large in multiprocessor

### ISSUE THREAD

**Issue by wajahat57** [kurapan/EAST#3]
Hi, 
I am getting this error. 
Did you every get any such error.
If so, can you please suggest how to resolve it?

```
  File "D:/Documents/PythonScripts/Keras_EAST/train.py", line 213, in main
    val_data = data_processor.load_data(FLAGS)

  File "D:\Documents\PythonScripts\Keras_EAST\data_processor.py", line 864, in load_data
    loaded_data = pool.map_async(load_data_process, zip(image_files, itertools.repeat(FLAGS), itertools.repeat(is_train))).get(9999999)

  File "c:\winpython\python-3.5.4.amd64\lib\multiprocessing\pool.py", line 638, in get
    self.wait(timeout)

  File "c:\winpython\python-3.5.4.amd64\lib\multiprocessing\pool.py", line 635, in wait
    self._event.wait(timeout)

  File "c:\winpython\python-3.5.4.amd64\lib\threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
```

**Comment by wajahat57** [comment]
The process I use is core i7 with 4 physical cores (2 logical cores/physical core).
I have tried by using 2 to 8 cores. 
But I get the same error.

**Comment by wajahat57** [comment]
Hi Kurapan
Thanks. Yeah, I checked on the internet and reducing get function values by one 9 at least, solves this problem. However, It keeps on loading the data and nothing shows on the command prompt . If I am using ICDAR data that you shared the link, just to get a successful attempt at training. It has 1229 images. 
With 6 workers, CPU processing on a corei7 goes from 20% to 90%. It stays there for 30 minutes and still not moving forward in the execution.

The display is holding on:
```
 runfile('D:/Documents/PythonScripts/Keras_EAST/train.py', args='--gpu_list=-1 --input_size=512 --batch_size=1 --nb_workers=6 --training_data_path="F:/TrainingData/EAST_Training/ICDAR2013+2015/train_data" --validation_data_path="F:/TrainingData/EAST_Training/ICDAR2013+2015/train_data" --checkpoint_path="tmp/ cdar2015_east_resnet50/"')
Reloaded modules: data_processor, model, adamw, losses
```

**Comment by wajahat57** [comment]
I am using 64 bit Python 3.5 on Windows 10, TensorFlow 1.10.0 and Keras 2.2.2

**Comment by wajahat57** [comment]
I am able to get it to start training on Ubuntu. I am not sure why it is not starting in Windows.
Is it possible for you to try it on Windows?

**Comment by kurapan** [comment]
It can take quite some time to load the data, but I guess it's some issue that halts the execution and it stays there indefinitely.

I could try running it on Windows in CPU mode on my laptop. Probably not today, but I'll try to test it in the following days. I actually haven't tried it out in CPU mode, either.

**Comment by wajahat57** [comment]
Hi Jan,
Meanwhile, can you please explain the rational behind using multiprocessing?
Is all the data being loaded into the RAM first? or multiprocessing is just creating a list of files in the target folders?

**Comment by jhaiWang** [comment]
Hello , when I loading the model , the error message is "No model found in config file" .  The model that you provide maybe something wrong , can you tell me what can I do to deal with the error message?

**Comment by jhaiWang** [comment]
Hello , when I loading the model , the error message is "No model found in config file" .  The model that you provide maybe something wrong , can you tell me what can I do to deal with the error message?
