### ISSUE TITLE
Query about  Transfer Learning?

### ISSUE THREAD

**Issue by cheeyeo** [kurapan/EAST#35]
HI, firstly this is a great library and great work on porting it over.

I have a query regarding using the precompiled EAST model for transfer learning? I am able to download and run the precompiled model but since my dataset is small, I thought the best approach is to apply transfer learning using the model as a feature extractor.

However,  I am trying to get the output of lower layers in the network rather than the higher layers?

Are there any approaches to this? Are there any specific layers I should get the output from?

Thank you for any advice / help.

**Comment by kurapan** [comment]
Hi! Thanks!

EAST is based on the U-Net architecture, so layers in different levels of depth are supposed to extract information of different detail. You have the encoder and decoder part and they are connected at each level. I haven't read any paper on transfer learning in scene text detection models and I can't recall anything about transfer learning using U-Nets. If I've read something then I've forgotten about it. I suppose that one could try to use the features from the last layer of the encoder, but if you use features only from that level, a lot of detail will probably be lost and you might not be able to detect small text. Or you could rather try using features from multiple levels in the encoder.
How small exactly is your dataset? The ICDAR 2015 dataset that is used for benchmarking scene text detection models is small, too. It's about 1000 images. And you can train a detector using that dataset from scratch.

**Comment by cheeyeo** [comment]
Hi, 

Thanks for the reply. You were right in pointing out that transfer learning may not be applicable in this case. My dataset is less than 1000 samples and its distribution also does not match that of the ICDAR 2015 dataset which comprises of natural scene text. I will try to collate more data and train a custom detector using your implementation here. Thanks for your advice.
