### ISSUE TITLE
how can i use the json model

### ISSUE THREAD

**Issue by fanfusuzi** [kurapan/EAST#37]
is there any code in your github to use the json model? I have trained the model and the model parameters have been saved in the json file.How can i use?

**Comment by kurapan** [comment]
You can use `eval.py` or use it as a reference for evaluation.

**Comment by fanfusuzi** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Thank you ,I'm using your code to train a data set for Identity document location. Do you think this code can be used for  Identity document  location
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                fanfusuzi
                            
                            
                                
                            
                    
                        
                            
                                    fanfusuzi@sjtu.edu.cn
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 12/19/2019 12:07，Jan Zdenek<notifications@github.com> wrote： 


You can use eval.py or use it as a reference for evaluation.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kurapan** [comment]
I have never heard about identity document location task so I don't know if it's applicable or not. Maybe you could try to explain it a bit more.
