### ISSUE TITLE
For Pages or Documents

### ISSUE THREAD

**Issue by WrathofBhuvan11** [kurapan/EAST#4]
How good is the result for pages...
Or Document images..?

**Comment by kurapan** [comment]
I haven't tried that. This method is designed for detection of text in images of outdoor or indoor scenes, aka scene text, and the papers proposing new methods for detection of scene text, including EAST, do not conduct experiments on documents.
In theory, it should be easy for the model to detect bounding boxes of text regions, but it only detects the boxes. For documents, you probably need to detect whole text lines and the flow of the paragraph as well, so you would have to implement some post-processing to link the detected bounding boxes in text lines, and the text lines in paragraphs.
