### ISSUE TITLE
AssertionError: can only join a child process

### ISSUE THREAD

**Issue by jhaggle** [kurapan/EAST#40]
Running the code gives this error:
File "/usr/lib/python3.6/multiprocessing/process.py", line 122, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process

The error comes from row 862 in the file data_processor.py
pool = Pool(FLAGS.nb_workers)

**Comment by jhaggle** [comment]
Note! This only happens when I run the code in the VSCODE debugger.

**Comment by kurapan** [comment]
I don't use VSCODE so I'm afraid I can't really comment on that. My guess would be that VSCODE debugger has some rules regarding multiprocessing that don't allow you to use multiprocessing in the same way as when you run the code regularly. Using debug mode in multiprocessing settings sound quite difficult to me.
