### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 

### ISSUE THREAD

**Issue by jhaggle** [kurapan/EAST#41]
I have created a virtual environment and runs 
 python3 -m pip install -r requirements.txt

I then get the following error:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hel5gym7/Shapely/

What is wrong?

**Comment by kurapan** [comment]
Maybe it's this issue? https://stackoverflow.com/questions/35991403/pip-install-unroll-python-setup-py-egg-info-failed-with-error-code-1
That would suggest you need to install setuptools package.
