### ISSUE TITLE
Ran out of input

### ISSUE THREAD

**Issue by conghieu135** [kurapan/EAST#42]
when i run use_multiprocessing = true have a error 
![image](https://user-images.githubusercontent.com/3182698/74500706-53174780-4f1a-11ea-86ef-985fcaaeed02.png)

and when use_multiprocessing = false, have error
![image](https://user-images.githubusercontent.com/3182698/74500743-78a45100-4f1a-11ea-84f6-aeac70420b9b.png)

**Comment by love6tao** [comment]
I also have the same error

**Comment by kurapan** [comment]
Hi! Are you still trying to resolve this issue? I know that the code doesn't seem to run well in Windows. Someone else has previously reported some issues when running it in Windows. Particularly multiprocessing doesn't seem to work. The issue when you don't use it seems to be related to dimensions of the input. What kind of input are you giving to the model?

**Comment by love6tao** [comment]
I successfully ran this program in windows, and tested the effect with eval.py, the effect is very common.
1) Windows and Ubuntu path / and \ problems will cause the image to not load in
2) Ubuntu is case sensitive and windows does not distinguish between JPG and jpg
3) The problem of reading txt, if the lack of utf-8 under windows will cause the error of the coordinate label
4) There is a problem with CustomTensorBoard and ValidationEvaluator, I canceled the related callback
5）use_multiprocessing=False

![image](https://user-images.githubusercontent.com/12590932/79119729-a34c4200-7dc3-11ea-96d1-a46c3cae8ae4.png)

**Comment by love6tao** [comment]
@conghieu135 The problem you meet is that you should 
 replace the line containing ZeroPadding2D with x = concatenate([x, resnet.get_layer('activation_10').output], axis=3).
