### ISSUE TITLE
killed

### ISSUE THREAD

**Issue by jhaggle** [kurapan/EAST#44]
Downloaded your code all over as well as the datasets ICDAR2013+2015 for training and val_data_latin for validation. Starting the training and it abruptly ends with "killed".

The last part of of the terminal output:
 Total params: 24,237,478
Trainable params: 24,183,398
Non-trainable params: 54,080
________________________________________________________________________________Epoch 1/3
12 training images in /home/johan/Documents/agellis_projects/temp/ICDAR2013+2015_12/train_data/
Killed

**Comment by kurapan** [comment]
Hi!
Were you able to solve this issue? If not I would probably have to know some more details about the environment you run it in to try to help you.
You only have 12 images in your training dataset?
