### ISSUE TITLE
Issue : Could not load pretrained model

### ISSUE THREAD

**Issue by TheRum** [kurapan/EAST#5]
Hi @kurapan,
When I am trying to load pretrained model, it is giving error "ValueError: No model found in config file.".
Can you please provide an updated model file ? Or help in rectifying this error.

Traceback (most recent call last):
  File "eval.py", line 195, in <module>
    main()
  File "eval.py", line 142, in main
    model = load_model('EAST_IC15_13_model.h5')
  File "/usr/local/lib/python3.6/site-packages/keras/engine/saving.py", line 258, in load_model
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.

Thank you.

**Comment by kurapan** [comment]
I'm not really sure what is the cause of the error so I will look into it in the following days.

**Comment by franciscoflorez** [comment]
Hi,

I have a similar error. While the model downloaded is 'EAST_IC15_13_model.h5', the code is trying to open 'model.json'. Therefore, they have different name and different format/extension

**Comment by kurapan** [comment]
Sorry for late response. I forgot to upload the JSON file. I've updated the readme file with a link to the JSON file.
You need to open the JSON and use `model_from_json()` to load the model defined in the JSON file. The weights in h5 file are loaded using `model.load_weights()` a line below that. Iirc, it threw some error saying it wasn't able to resolve the custom objects used in the model when using `load_model`. The uploaded h5 file only contains the weights.
