### ISSUE TITLE
No such layer: activation_49

### ISSUE THREAD

**Issue by germanebr** [kurapan/EAST#59]
Hello, I'm trying to run your EAST code in Windows, but I've been having some problems when running the training script.

The error is the following:
`Number of validation images : 0
Training with 1 GPU
Traceback (most recent call last):

  File "D:\Users\GermanEBR\Glite\ITESM\DCI\Enero Mayo 2020\Challenge 2\Challenge 2_Germán Baltazar A01331329.py", line 261, in <module>
    main()

  File "D:\Users\GermanEBR\Glite\ITESM\DCI\Enero Mayo 2020\Challenge 2\Challenge 2_Germán Baltazar A01331329.py", line 225, in main
    east = EAST_model(FLAGS.input_size)

  File "D:\Users\GermanEBR\Glite\ITESM\DCI\Enero Mayo 2020\Challenge 2\model.py", line 30, in __init__
    x = resnet.get_layer('activation_49').output

  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\keras\engine\network.py", line 365, in get_layer
    raise ValueError('No such layer: ' + name)

ValueError: No such layer: activation_49`

I'm using TensorFlow 2.1.0 and Keras 2.3.1 in Python 3.7.7
I don't know why the problem is the search of the activation function of the resnet activation function.

Thanks for your support and for the code.

**Comment by vamsireddy01** [comment]
I am facing the same issue. 

raise ValueError('No such layer: ' + name)
ValueError: No such layer: activation_49

**Comment by Marisamy01** [comment]
> Hello, I'm trying to run your EAST code in Windows, but I've been having some problems when running the training script.
> 
> The error is the following:
> `Number of validation images : 0
> Training with 1 GPU
> Traceback (most recent call last):
> 
> File "D:\Users\GermanEBR\Glite\ITESM\DCI\Enero Mayo 2020\Challenge 2\Challenge 2_Germán Baltazar A01331329.py", line 261, in
> main()
> 
> File "D:\Users\GermanEBR\Glite\ITESM\DCI\Enero Mayo 2020\Challenge 2\Challenge 2_Germán Baltazar A01331329.py", line 225, in main
> east = EAST_model(FLAGS.input_size)
> 
> File "D:\Users\GermanEBR\Glite\ITESM\DCI\Enero Mayo 2020\Challenge 2\model.py", line 30, in **init**
> x = resnet.get_layer('activation_49').output
> 
> File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\keras\engine\network.py", line 365, in get_layer
> raise ValueError('No such layer: ' + name)
> 
> ValueError: No such layer: activation_49`
> 
> I'm using TensorFlow 2.1.0 and Keras 2.3.1 in Python 3.7.7
> I don't know why the problem is the search of the activation function of the resnet activation function.
> 
> Thanks for your support and for the code.

I am also facing the same problem, If you solved that issue please help me
