### ISSUE TITLE
data_processor: Undefined variable

### ISSUE THREAD

**Issue by C0conuts** [kurapan/EAST#7]
Line 479 and 481 in data_processor you have "overly_small_text_mask" which doesn't exist.
Should be "overly_small_text_region_training_mask".
This will generate errors when loading validation data for some reason.

Then line 693 still in data_processor you have "im_padded" which doesn't exist neither. It should be "im" considering the line above.

**Comment by kurapan** [comment]
Thanks for pointing out the issues. I ran the training code as it is before putting in on github so it's kind of weird that there are variable name issues, but I'll look at it and fix it asap.

**Comment by C0conuts** [comment]
Hi Kurapan,
These errors only break the validation pipeline, not the training. And as is, validation is ran each 5 epochs (value I've changed to 1). Have you ever trained more than 5 epochs?

**Comment by kurapan** [comment]
Sorry it took a while, but it should be fixed now

**Comment by NidhiSultan** [comment]
@C0conuts , can you help with an issue while loading Validation data. It doesn't throw any error but multiprocessing loader variable gives me an empty list. Somehow Load_annoation doesn't work fine for me.
Thanks in advance!!
