### ISSUE TITLE
Locality Aware NMS as separate package

### ISSUE THREAD

**Issue by safijari** [kurapan/EAST#8]
The bit where you compile the NMS package is ... brilliant ... if a bit scary. It might be a bit cleaner if that was its own separate package on PyPI and this package were purely python.

I can help get that done and build self contained wheels for it as well (at least for Linux). Interested?

**Comment by C0conuts** [comment]
Hi! 
So if you check the eval.py file, you'll see a line commented out on line 99.
You'll see the "import locality_aware_nms as nms_locality" at the beginning of the file too which imports the script in the locality_aware_nms.py file.
So you can uncomment line 99 and comment out line 100 and then nms is done using this script and not the one that needs to be compiled using g++ (lanms). 
Know that it's slower though.

**Comment by safijari** [comment]
I don't have any issues importing lanms, was just wondering if splitting it out might be useful.

**Comment by kurapan** [comment]
Hi!
Thanks for the suggestion. The lanms code is taken from the original Tensorflow implementation of EAST, so I'm not really sure how kosher it would be to put the code on PyPI without the permission of the original author. What's your opinion on that?
Unfortunately, the authors of the original Tensorflow repo are not very responsive so trying asking them for permission might not help. Maybe I'll try opening an issue there anyway or you could try it if you want.

**Comment by safijari** [comment]
Sure. If we don't hear back I don't personally have any issue with putting the code on PyPI (I guess we should check to see if it has a license) so long we attribute it back to who we think is the original author.
