### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by vinothkumarsvv** [kurapan/EAST#9]
Traceback (most recent call last):
  File "train.py", line 249, in <module>
    main()
  File "train.py", line 246, in main
    history = parallel_model.fit_generator(train_data_generator, epochs=FLAGS.max_epochs, steps_per_epoch=train_samples_count/FLAGS.batch_size, use_multiprocessing=False, callbacks=callbacks, verbose=1)
  File "C:\Users\VINOTH KUMAR S\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\VINOTH KUMAR S\Anaconda3\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\VINOTH KUMAR S\Anaconda3\lib\site-packages\keras\engine\training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\VINOTH KUMAR S\Anaconda3\lib\site-packages\keras\callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "train.py", line 104, in on_epoch_end
    input_image_summary = make_image_summary(((data[0][0][i] + 1) * 127.5).astype('uint8'))
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by vinothkumarsvv** [comment]
i am getting this error while running the train.py code...please tell me the way to clear this error

**Comment by kurapan** [comment]
What data do you use for training? Is it that ICDAR dataset?

**Comment by vinothkumarsvv** [comment]
yes .I am using ICDAR2013+2015 data set.

**Comment by kurapan** [comment]
Something seems to be wrong with the `data_generator` output.
What batch size do you use?

**Comment by vinothkumarsvv** [comment]
the batch size i am using is 16

**Comment by kurapan** [comment]
Could you print out the output of this line? https://github.com/kurapan/EAST/blob/master/train.py#L100
Maybe just the shape of `data` variable. Something like `print(data.shape)`.
Tell me your keras and tf version too, just in case.

**Comment by vinothkumarsvv** [comment]
![screenshot 232](https://user-images.githubusercontent.com/47805732/53386939-7021d600-39aa-11e9-903b-3415fe9c05d0.png)

**Comment by vinothkumarsvv** [comment]
I am getting this error..and program did not ends

**Comment by kurapan** [comment]
I can't see any information related to my code from this screenshot.
Please copypaste the entire message related to the error.
And as I said, print out the shape of `data` variable that is declared on line 100.
Have you made any changes to the code? I don't remember seeing this kind of output with the filenames.

**Comment by vinothkumarsvv** [comment]
(base) F:\New folder\EAST-master>python train.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 249, in <module>
    main()
  File "train.py", line 213, in main
    val_data = data_processor.load_data(FLAGS)
  File "F:\New folder\EAST-master\data_processor.py", line 864, in load_data
    loaded_data = pool.map_async(load_data_process, zip(image_files, itertools.repeat(FLAGS), itertools.repeat(is_train))).get(9999999)
  File "C:\Users\VINOTH KUMAR S\Anaconda3\lib\multiprocessing\pool.py", line 651, in get
    self.wait(timeout)
  File "C:\Users\VINOTH KUMAR S\Anaconda3\lib\multiprocessing\pool.py", line 648, in wait
    self._event.wait(timeout)
  File "C:\Users\VINOTH KUMAR S\Anaconda3\lib\threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\VINOTH KUMAR S\Anaconda3\lib\threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
OverflowError: timeout value is too large

**Comment by vinothkumarsvv** [comment]
when I run the code without any changes(as it is)with my dataset directory, I am getting this error.please tell me the reason for this error

**Comment by kurapan** [comment]
Ah, the timeout value overflow error is some Windows issue. I haven't tested it in Windows as I don't have access to any Windows machine that could be used for machine learning.
Try a number lower than that `9999999`.

You were able to resolve this with some changes?

**Comment by vinothkumarsvv** [comment]
(base) F:\New folder\EAST-master>python train.py
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_201.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_207.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_204.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_210.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_202.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_208.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_205.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_211.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_203.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_209.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_206.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_212.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_213.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_219.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_202.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_216.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_203.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_214.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_220.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_217.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_204.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_201.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_215.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_205.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_218.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_208.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_211.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_206.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_214.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_209.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_212.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_207.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_215.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_210.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_213.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_217.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_216.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_220.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_218.txt does not exists
text file gt_F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_219.txt does not exists
Number of validation images : 0
Training with 1 GPU
WARNING:tensorflow:From C:\Users\VINOTH KUMAR S\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-02-26 11:35:33.744607: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
C:\Users\VINOTH KUMAR S\Anaconda3\lib\site-packages\keras_applications\resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '
______________________________________________________________________

**Comment by vinothkumarsvv** [comment]
when i reduced the number ..the program run..but it doesn't consider the image file..I run the train.py with only 20 validation images and 20 data set images. just for checking...will this be a problem.?

**Comment by kurapan** [comment]
It says there are no validation images and that the txt files don't exist. Is the path correct?

**Comment by vinothkumarsvv** [comment]
yes,the path is correct

**Comment by kurapan** [comment]
Are there really files `img_XXX.txt` in the `val_data_latin` directory?

**Comment by vinothkumarsvv** [comment]
yes sir,the img_xxx.jpg and gt_img_xxx.txt are in same directory

**Comment by vinothkumarsvv** [comment]
but the image.jpg files are read as  image.txt files..

**Comment by kurapan** [comment]
I see one problem now. Windows uses backslash instead of slash. Change it in the `get_text_file` function.

**Comment by vinothkumarsvv** [comment]
-----------
img_ (5).txt
text file F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\gt_img_ (5).txt does not exists
F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_ (6).txt
-----------
img_ (6).txt
text file F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\gt_img_ (6).txt does not exists
F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_ (7).txt
-----------
img_ (7).txt
text file F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\gt_img_ (7).txt does not exists
F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_ (8).txt
-----------
img_ (8).txt
text file F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\gt_img_ (8).txt does not exists
F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\img_ (9).txt
-----------
img_ (9).txt
text file F:\EAST\Dataset\MLT_val_data_latin\val_data_latin\gt_img_ (9).txt does not exists
Number of validation images : 0
Training with 1 GPU
WARNING:tensorflow:From C:\Users\VINOTH KUMAR S\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-02-26 14:08:58.687619: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
C:\Users\VINOTH KUMAR S\Anaconda3\lib\site-packages\keras_applications\resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)`

**Comment by vinothkumarsvv** [comment]
I am getting this error  when i renamed from gt_img.txt to get_img.txt

**Comment by vinothkumarsvv** [comment]
img_ (13).txt
    main()
  File "train.py", line 248, in main
    , callbacks=callbacks, verbose=1)
  File "C:\Users\VINOTH KUMAR S\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
################################# F:\EAST\Dataset\ICDAR2013+2015\ICDAR2013+2015\train_data\img_ (20).jpg
F:\EAST\Dataset\ICDAR2013+2015\ICDAR2013+2015\train_data\img_ (20).txt
-----------
img_ (20).txt
    return func(*args, **kwargs)
  File "C:\Users\VINOTH KUMAR S\Anaconda3\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\VINOTH KUMAR S\Anaconda3\lib\site-packages\keras\engine\training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "C:\Users\VINOTH KUMAR S\Anaconda3\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Users\VINOTH KUMAR S\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
################################# F:\EAST\Dataset\ICDAR2013+2015\ICDAR2013+2015\train_data\img_ (17).jpg
F:\EAST\Dataset\ICDAR2013+2015\ICDAR2013+2015\train_data\img_ (17).txt
-----------
img_ (17).txt
################################# F:\EAST\Dataset\ICDAR2013+2015\ICDAR2013+2015\train_data\img_ (10).jpg
F:\EAST\Dataset\ICDAR2013+2015\ICDAR2013+2015\train_data\img_ (10).txt
-----------
img_ (10).txt
    return self._call(inputs)
  File "C:\Users\VINOTH KUMAR S\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\VINOTH KUMAR S\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "C:\Users\VINOTH KUMAR S\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
################################# F:\EAST\Dataset\ICDAR2013+2015\ICDAR2013+2015\train_data\img_ (14).jpg
F:\EAST\Dataset\ICDAR2013+2015\ICDAR2013+2015\train_data\img_ (14).txt
-----------
img_ (14).txt
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [16,64,64,1] vs. [16,128,128,1]
         [[{{node loss/pred_score_map_loss/mul_4}}]]

**Comment by vinothkumarsvv** [comment]
i am getting this error when the train.py program is executed

**Comment by kurapan** [comment]
Could you tell me what changes you have made to the code?
I don't know how to reproduce your error so you have to tell me more.
